name: Release

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Calculate SHA256
        id: sha256
        run: |
          SHA256=$(shasum -a 256 docfx-unity-docusaurus.sh | awk '{print $1}')
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT

      - name: Checkout tap repository
        uses: actions/checkout@v3
        with:
          repository: mgamesdev/homebrew-unity-docfx-docusaurus
          token: ${{ secrets.GITHUB_TOKEN }}
          path: homebrew-tap

      - name: Create Formula directory
        run: mkdir -p homebrew-tap/Formula

      - name: Copy script to tap
        run: cp docfx-unity-docusaurus.sh homebrew-tap/Formula/

      - name: Copy and update formula
        env:
          SHA256: ${{ steps.sha256.outputs.sha256 }}
        run: |
          # Extract version from tag (remove 'v' prefix)
          VERSION=${GITHUB_REF#refs/tags/v}
          
          # Construct the release URL
          RELEASE_URL="https://github.com/mgamesdev/unity-docfx-docusaurus/archive/refs/tags/v${VERSION}.tar.gz"
          
          # Copy the formula template
          cp Formula/unity-docfx-docusaurus.rb homebrew-tap/Formula/
          
          # Update the placeholders
          sed -i '' "s|RELEASE_URL_PLACEHOLDER|$RELEASE_URL|" homebrew-tap/Formula/unity-docfx-docusaurus.rb
          sed -i '' "s|SHA256_PLACEHOLDER|$SHA256|" homebrew-tap/Formula/unity-docfx-docusaurus.rb

      - name: Commit and push changes
        run: |
          cd homebrew-tap
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/
          git diff --staged --quiet || git commit -m "Update formula for ${{ github.ref }}"
          git push 