name: Release

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Calculate SHA256
        id: sha256
        run: |
          SHA256=$(shasum -a 256 docfx-unity-docusaurus.sh | awk '{print $1}')
          echo "::set-output name=sha256::$SHA256"

      - name: Update Homebrew formula
        run: |
          # Extract version from tag (remove 'v' prefix)
          # Example: refs/tags/v1.0.0 -> 1.0.0
          VERSION=${GITHUB_REF#refs/tags/v}
          
          # Construct the release URL
          # Example: 1.0.0 -> https://github.com/mgamesdev/unity-docfx-docusaurus/archive/refs/tags/v1.0.0.tar.gz
          RELEASE_URL="https://github.com/mgamesdev/unity-docfx-docusaurus/archive/refs/tags/v${VERSION}.tar.gz"
          
          echo "Updating formula with:"
          echo "Version: ${VERSION}"
          echo "URL: ${RELEASE_URL}"
          echo "SHA256: ${{ steps.sha256.outputs.sha256 }}"
          
          # Update the formula with the new URL and SHA256
          sed -i '' "s|url \".*\"|url \"${RELEASE_URL}\"|" Formula/unity-docfx-docusaurus.rb
          sed -i '' "s/sha256 \".*\"/sha256 \"${{ steps.sha256.outputs.sha256 }}\"/" Formula/unity-docfx-docusaurus.rb

      - name: Create tap repository
        run: |
          # Clone using public URL
          if ! git clone https://github.com/mgamesdev/homebrew-unity-docfx-docusaurus.git; then
            echo "Failed to clone tap repository. Please ensure the repository exists at https://github.com/mgamesdev/homebrew-unity-docfx-docusaurus"
            exit 1
          fi
          
          cd homebrew-unity-docfx-docusaurus
          cp ../docfx-unity-docusaurus.sh Formula/
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Formula/unity-docfx-docusaurus.rb
          git commit -m "Update formula to ${{ github.ref }}"
          
          # Use token only for push
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "Error: GITHUB_TOKEN is not available"
            exit 1
          fi
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/mgamesdev/homebrew-unity-docfx-docusaurus.git 